### ISSUE TITLE
Civi Products : To be or not to be + wondering on how and what

### ISSUE THREAD

**Issue by jbonlinea** [WPCV/wpcv-woo-civi-integration#13]
folowing up #7  in smaller part

> > why create CiviProduct for Contribution/membership/participation while we can use a woo simple product to create a contribution/membership/participation ?
> 
> @jbonlinea Good question - it's an experiment to see if there are advantages. I may switch them off if there don't prove to be useful enough. 

Ok, I understand the need for experiment :)

> What they do avoid is the slightly confusing "CiviCRM Entity" selector on Simple Products and enforce the "Is Virtual" and "Is Downloadable" settings.

Oh ? ah ? 

As far I have seen an order paid online via credit card, and containing only a product that is "virtual" and "downloadable", will have the statute "completed" right at the end of the order, and won't have the "processing" statute first.

My testing regarding the maping WooOrder statut  <-> CiviContribution shows that an order with a CiviCRM Product paid by credit card has "processing" statute and not "completed" see #11 

 This suggest that the CiviCRM product are not "virtual" and "downloadable". as you seems to advance (or maybe I missunderstood).

Nevertheless a SimpleWooProduct set as virtual and downloadable, containing a CiviSyc (contribution/membership/participation) will have the "completed' woo statute if paid by credit card :)

> Personally I would prefer it if Simple Products only mapped to Contributions - it's a bit weird (in my opinion) that buying a t-shirt can grant a CiviCRM Membership - but that is, at present, perfectly possible. I guess that gives the plugin greater flexibility, so it's not something I plan to change.

Yep, either works :)

It is true that buying a t-shirt could grant a CiviMembership is a bit weird. And I agree that it should be thought the other way round, you get to be a member, and might have a gift (to use Civi language)

But when we create a CiviMembership product, we have to name and describe it, and nothing prevent us from naming and describing a simple product the exact same way. If done so, then there wouldn't be any difference between the product itself, but only in the way we set it to be synced in Civi.

So it's tomatoes and tomatoes functionality wise and front-end UX wise. But  if having a CiviMembership product might have a point just because it materialize the obviousness that we must define the membership type, CiviPriceSet and etc to sync it in Civi, I'm not sure that having two option to achieve the same thing, or the lack of consistency on how to set civi syncing won't be confusing for the editor/shop manager/NGO administrator.

More over, this may be the moment to speak about Gifts in Civi, and how they may be handled from Woo. I don't use it or mind about that, but I could as one of my case study do "offer" an electronic/paper version of the scientific journal they publish when someone is a member (I do have used one CiviMember custom field to collect the wish of the member on registration). 

I don't know more than I know in this respect, but a woo product approach may unlock that simply ? The product you buy is membership+giftX, membership+gifY (which coud be two different products or a variation ?)
Or on the contrary, maybe a CiviProduct with membership could, when added in your cart, change other product price (to 0 in some cases) that are then CiviCRM Gifts ? 
I dontt know, I'm just thnking loudly.

One thing is sure thow. If Civi Product remains, they really NEED to offer the option to set whether they are virtual and downloadable. My case of the membership which opens up for a free copy of a paper version of the journal is just one example of how setting the mebership produc in woo as not virtual is a great way for the editor/shop manager/NGO administrator to track if the order is done (virtual downloadable version of the journal) or have to be processed (send the paper copy).

> I'm still in the process of making the plugin truly aware of (and respect the differences of) the different kinds of Woo Product Types - currently working on Variable Products on which front you should see progress soon.

yes I thought about that, and it's intertwining with Civi Custom field :) 

---

Ok that's it for today I think :)

Again, thank you very much for this great piece ! 

Have a pleasant day @christianwach 

Cheers

**Comment by christianwach** [comment]
@jbonlinea I have removed the Custom Product Types (except for developers).

**Comment by jbonlinea** [comment]
> > More over, this may be the moment to speak about Gifts in Civi
> 
> This would be better in a separate issue, but I'll deal with it briefly here to say that there are a number of approaches you could take to implement this:
> 


yes for sure, this was a side note ;)

**Comment by jbonlinea** [comment]
> @jbonlinea I have removed the Custom Product Types (except for developers) in #19

ok, I think it's easier this way :)
