### ISSUE TITLE
Orders not coming up in contributions, but showing in woo-orders tab

### ISSUE THREAD

**Issue by netzih** [WPCV/wpcv-woo-civi-integration#29]
Just installed the plugin,
Created an order to test it, But it did not create a contribution.
The order shows up in the woo-orders tab, but no new contributions came up.
Went through the civi logs and not seeing anything that would cause that.
Any ideas? (Or did I misunderstand and it is not supposed to create a contribution?)

**Comment by christianwach** [comment]
@netzih How did you create the order?

**Comment by netzih** [comment]
@christianwach I opened another browser and placed an order while not logged in.

**Comment by netzih** [comment]
Sure.
I'll post those, as well as the contact info on civi as well so you can see.
![image](https://user-images.githubusercontent.com/48005023/165573429-9b90d929-70b4-40b7-8c31-118ece61e270.png)
![image](https://user-images.githubusercontent.com/48005023/165573800-2a86b075-1e22-47b0-9407-ce9677e149e1.png)
![image](https://user-images.githubusercontent.com/48005023/165574884-fe7953fa-f83a-49f2-8ef6-686d2b0b371f.png)
![image](https://user-images.githubusercontent.com/48005023/165575137-c37210bf-55b4-4aae-8477-9aa1261aad96.png)

**Comment by christianwach** [comment]
@netzih Looks like you need to fill out the Woo Settings in their entirety - particularly "Product Types with CiviCRM Settings" and "Pay Later Methods". You also have to specify a "Price Field Value" for the Product.

**Comment by netzih** [comment]
@christianwach Looks like the only setting I missed was the product types with CiviCRM settings, Price field value was not necessary.
I'm going to keep this issue open for another day or 2 to make sure everything is working out before closing it.
Thanks.

**Comment by netzih** [comment]
Does it not work for variable products?
I can only choose simple products and not variable.

**Comment by christianwach** [comment]
> Price field value was not necessary.

@netzih I highly recommend you set the Price Field Value. Odd things happen when it's not set.

> Does it not work for variable products?

It does work with Variable Products, but works best under certain conditions, e.g. when generated by the Settings Metabox for a CiviEvent with a Price Set. The Price Field Values become the Variations.

Have a play with the Variable Product UI to see what's possible.

**Comment by christianwach** [comment]
Closing as I assume this is fixed.
