### ISSUE TITLE
CiviCRM / Woocommerce- Not showing Membership Type or Price Field

### ISSUE THREAD

**Issue by tgreer** [WPCV/wpcv-woo-civi-integration#34]
Hi

I've got a fresh install of Wordpress (6.0), CiviCRM (5.50.1) and WooCommerce (6.5.1). Plugin is version 3.0, which was freshly pulled from the github repo today.

I've setup an organisation and in Civi Membership I've setup 2 membership types with prices.

When I try to add them to a product and change the dropdown to CiviCRM Membership or Event I don't get presented the additional fields needed.
![nosettings](https://user-images.githubusercontent.com/4996098/172708110-a75824ef-bf17-41dd-a766-d53664afc525.png)

Am I missing something obvious?

Thanks in advance.

Thomas

**Comment by christianwach** [comment]
@tgreer The only thing I can think of is that you may not have any Membership Types (and/or Price Sets) configured. Otherwise, is there anything in your logs to indicate an error?

**Comment by tgreer** [comment]
@christianwach  I'll have another go over and see. Thank you for taking the time out to repond. By logs do you mean webserver logs or anything else in particular?

**Comment by tgreer** [comment]
@christianwach great thanks, I'll review all of the above and feedback. Hopefully I've just missed something obvious and in that case apologies in advance for wasting your time.

**Comment by christianwach** [comment]
@tgreer Well yes... sort of... CiviCRM actually creates "virtual" Price Sets if you fill out the prices when creating the Event or Membership. These *should* show up in the relevant drop-downs.

**Comment by christianwach** [comment]
@tgreer I'd recommend installing the "Sample Data" on a disposable CiviCRM instance if you're new to it. the sample data will show you how many of the CiviCRM components should look when they're properly configured. Otherwise, the [docs](https://docs.civicrm.org/user/en/latest/membership/defining-memberships/) (this link is for Memberships) are a good source of information.

**Comment by tgreer** [comment]
@christianwach Thanks. I'll close this issue off them. Appreciate your time.
