### ISSUE TITLE
Group product

### ISSUE THREAD

**Issue by lesleyjill** [WPCV/wpcv-woo-civi-integration#40]
Fabulous plugin!
Any chance it can work with group product type.
Currently simple product seems to be the only choice.

**Comment by christianwach** [comment]
@lesleyjill What seems to be the problem you're having with the Group Product?

The CiviCRM Settings do indeed have to be applied to each Simple Product in the Group - but when a Group Product is purchased, the Contributions, Memberships etc that make up the Group Product are synced to CiviCRM.

FYI Variable Products are also supported, though the docs don't yet reflect that. You can automate the creation of a Variable Product for an Event via "CiviCRM" --> " WooCommerce" in WordPress admin. Or you can create one manually via "New Product", select the "CiviCRM Entity", then configure the Variations in the UI.

**Comment by christianwach** [comment]
> Currently simple product seems to be the only choice.

Hmm, I assume you're referring to the multi-select in the "CiviCRM" sub-tab of "WooCommerce Settings". This doesn't show Variable Product because it doesn't share the same UI as a Simple Product. If you had additional Product Types installed (e.g. via a plugin) that extend the Simple Product, then they would show up in that list.

**Comment by lesleyjill** [comment]
Thanks Christian - it works fine with group product - I just hadn't got to grips with WooCommerce yet. It works beautifully for donations (contributions), especially with this overlay https://wordpress.org/plugins/wc-donation-platform/.
I'm thinking it would be great for membership plus donation pages as well.
