### ISSUE TITLE
Help change license to allow listing in WP directory

### ISSUE THREAD

**Issue by JoeMurray** [WPCV/wpcv-woo-civi-integration#42]
There is a requirement that software be licensed as GPLv2 for it to be listing in the WordPress plugin directory. This repo has a complicated history of AGPLv3 and GPLv3. All contributors to the code that is part of the current master branch would need to relicense their contributions as GPLv2 to allow this to happen. @christianwach and @JoeMurray are interested in this. @bastienho @mecachisenros @rajeshrhino @cdhassell @agileware-fj @lukeyangjma @agileware-pengyi @yashodha @sabrinaleroy @kcristiano @veda-consulting would you be willing to have your contributions' license changed to GPLv2?

**Comment by kcristiano** [comment]
I am fine with the change

**Comment by cdhassell** [comment]
I am also fine with the change.

**Comment by bastienho** [comment]
No problem for me

21 oct. 2022 21:35:30 cdhassell ***@***.***>:

**Comment by lukewarmtemp** [comment]
I am fine with the change. As I don't have access to @lukeyangjma anymore, I'm responding from my personal account.

**Comment by JoeMurray** [comment]
I think we are pretty good to go if @rajeshrhino gives their consent.

**Comment by yashodha** [comment]
@yashodha no worries

**Comment by agileware-fj** [comment]
Apologies, didn't see the notification for this one until today. Nominally happy with relicensing to GPLv2, not that it necessarily matters according to Christian's audit.

**Comment by christianwach** [comment]
Pinging @rajeshrhino hope you have a moment to comment here. Thanks!

**Comment by christianwach** [comment]
@rajeshrhino Hoping to get your feedback on this issue once more. Apologies to others for the notification.

**Comment by JoeMurray** [comment]
@rajeshrhino I see you have been doing commits in github the last couple of months, we're reaching out to you. What we are hoping you could contribute here is a comment saying something like, "I agree to have my contributions to this repo changed to GPLv2."

**Comment by rajeshrhino** [comment]
I agree to have my contributions to this repo changed to GPLv2.

Apologies for the delay.
