### ISSUE TITLE
Plug-in behaviour : Order/Contribution <-->  Membership/Participation statute AND Woo Price <--> CiviPrice set intertwining

### ISSUE THREAD

**Issue by jbonlinea** [WPCV/wpcv-woo-civi-integration#7]
Hi there :)

### Thirst thing first : wow ! or shoud I say woow ! or woow thank's a lot !

--- 
#### Special words for the first issue
As this this the first issue of this awesome module, let me add that this basically enable to bring together website, membership, event registration and management, sale, and accounting, relying on open source only software ! 

Basically you get WP+WOO for front end publishing and payment, Civi for membership and event management (registration is truely displaced into woo), and WOO+Dolibarr (thank's to woosync) to push woo transaction into a real ERP with serious accounting capabilities (far beyound wp-erp). 

The only remaining question that will most probably be answered along this plug-in life is how well it will work when using wp forms plug-ins (name the one you prefer) to create woo customers and orders.

but hey, woow thank's ! 

---

Ok now let's get into business :)

I've done a quick (not so quick)  set up and testing :)

When one pass an order from woo front end shop page
- the order indded apears on civi contact "woo order" tab !
- if the product type is "simple product" (for instance) then a civi contribution is created, but it is always marked as "pending incomplete" event if I use stripe (in test mode) to make the payment in woo. 
- if the product type is civicrm participant, the order apears in civi woo tab, but no participation is added, even if the order is paid by stripe (test mode)  and "finished"
- if the product type is civicrm membership, the order apears in civi woo tab, but no membership is added, even if the order is paid by stripe (test mode)  and "finished

Note that's I've tried to pass order with various wp user, among admin, to avoid "capabilities" issue, but with no luck ! 

I'm on wp 5.8.2
Civi 5.43.2
Woo 5.9
and today git clone of this repo
PHP 7.4

So I may have missed something in the configuration or there is a small bug somewhere :)

Thank's again for this awesome initiative and work ! 

Cheers

Here you have some screenshot of my UI, which slightly differs from the one on the read-me

![Capture d’écran du 2021-11-20 16-23-23](https://user-images.githubusercontent.com/23659411/142733646-17f4620b-1e18-4a1b-ad1f-919e40f3d6ce.png)

![Capture d’écran du 2021-11-20 16-25-13](https://user-images.githubusercontent.com/23659411/142733653-83f8d99f-d17c-411c-be00-9842145b253e.png)

**Comment by christianwach** [comment]
@jbonlinea You should have "Price Field Value" as an option too. Can you make sure you have the recent [Allow Price Sets to be built regardless of CiviCRM tax rates](a6a3e3d2dcd1042323cc86b4abbe73483cabc13a) commit?

**Comment by jbonlinea** [comment]
Hi @christianwach  :)

Yes 100%, I did clone the repo a couple of hours before opening the issue, and to make sure there were no change I just have done a `git pull` which returned `Already up-to-date.`

However I did not have set any pricing in Civi. I just did, and indeed a price field apears... THEN

Passing an order for a "CiviCRM membership product"
- add an entry in the contact woo-order tab
- add a contribution, which amount is the product price and not the "value" of the Civi Princing
- add a membership

yay ! 

However, I may have some feedback about the syncing behaviour of  contributions.
The bottom line question is, may we map woo order statut to civi contribution staut ? 

the reason for asking is that when the order is passed in Woo and paid by credit card (stripe in test mode), the order statut is "processing" which might makes sense as organisation/siteOwner may really need "process" a "membership" or a "participation".

But it is synced in Civi as "pending" and "waiting for payment" while it's not waiting for payment.
The idea i that the contribution is paid, and the membership is active as soon as the payment is received, despite there may be some further processing needed (like sending a welcome letter, a journal, name your needs)

Conversely, a membership may only be a "membership" without further processing need to be "complete" so it would be nice if Civi membership product could be set as "virtual" and finished as soon as it is paid like woo simple products set s virtual products.

This also stand for CiviCRM participation product, processing might or not be needed for finish the event registration :)

Cheers

**Comment by christianwach** [comment]
@jbonlinea Thanks for the feedback. I'm not really sure where to start with an answer. Perhaps in future, you could break things up into bite-size chunks? That would really help!

> if setting a CiviPriceSet is indeed required to create membership and participation, then this could be mentioned in the readme

Agreed. As usual, you're an early adopter of plugins, so you're testing it in a development stage. The readme will be enhanced once the functionality is settled - which it isn't at this stage.

> Nevertheless, to my understanding if someone pass and pay an order for membership or participation, hes membership or participation should be "valid" immediately despite the contribution statut is "pending".

CiviCRM handles this via the Order API and Payment API. In my testing, CiviCRM does exactly what it should when the various parameters are set - i.e. Memberships and Participants are created and have their respective statuses set correctly. FYI, the requirement for a Price Field Value is to make CiviCRM behave itself.

**Comment by christianwach** [comment]
> why create CiviProduct for Contribution/membership/participation while we can use a woo simple product to create a contribution/membership/participation ?

@jbonlinea Good question - it's an experiment to see if there are advantages. I may switch them off if there don't prove to be enough. What they do avoid is the slightly confusing "CiviCRM Entity" selector on Simple Products and enforce the "Is Virtual" setting.

Personally I would prefer it if Simple Products only mapped to Contributions - it's a bit weird (in my opinion) that buying a t-shirt can grant a CiviCRM Membership - but that is, at present, perfectly possible. I guess that gives the plugin greater flexibility, so it's not something I plan to change.

I'm still in the process of making the plugin truly aware of (and respect the differences of) the different kinds of Woo Product Types. I'm currently working on Variable Products and you should see progress soon.

**Comment by jbonlinea** [comment]
Hi :)

> @jbonlinea Thanks for the feedback. I'm not really sure where to start with an answer. Perhaps in future, you could break things up into bite-size chunks? That would really help!
> 

Yes yes, it started form a bug or a set of bug not very well narrowed down to end in a first post broad feedback, but I'll open single ticket from now on

> > if setting a CiviPriceSet is indeed required to create membership and participation, then this could be mentioned in the readme
> 
> Agreed. As usual, you're an early adopter of plugins, so you're testing it in a development stage. The readme will be enhanced once the functionality is settled - which it isn't at this stage.
> 
Yes yes, no worries, 
I mentionend it as i couldn't know if it was a bug, or a setting requirement, and other might as well, but now they can find it in the issue at least ;)

I'm happy to be an early adopter especially if my experience help you in some way, and do not hesitate to reach me (here or by email as you have it) if you want any help for anything, I'll do it with pleasure if I can :)


---
I'll answer to the rest on separated issue to simplify the follow up :)
