### ISSUE TITLE
CiviCRM Participant product type : not saving the event

### ISSUE THREAD

**Issue by jbonlinea** [WPCV/wpcv-woo-civi-integration#8]
Hi there

I'm testing this peace of greatness and bumped into an issue.

- I do have created a woo product of type `CiviCRM pariticipant`
- the `CiviCRM setting` tab of the product is indeed asking me a financial type, an event, and a participant role, that I select for each
- I save my product, and thus the page reloads, and I see that the "event" field is empty ?!

This may to some extend explain why I can't register to an event from a woo order, see issue #7 

Cheers

**Comment by jbonlinea** [comment]
Hi, just a small bump here to say that despite I'have added a pricing, set this pricing for event in Civi, and have added a pricing to an event product in woo, the product do not save the selected event.

Regards

**Comment by christianwach** [comment]
Okay, thanks @jbonlinea I see that now. Strange - it used to work!

**Comment by christianwach** [comment]
@jbonlinea Latest merge should fix this. Thanks for reporting the bug.

**Comment by christianwach** [comment]
I'm not sure whether this fix will address your report of a Participant not being created when the Order is created and Payment made. I'll check that process later.

Also FYI the Event ID was being saved but not set properly when the Edit Product page was loaded, so the Event ID *should* have been retrieved during the Order/Payment process.

**Comment by jbonlinea** [comment]
Hi @christianwach 

Super quick, and super efficient, as ever :+1: 

Notable changes :
- yes, the event selected in the product is now saved AND visible :)
- yes the participant is created as well
  - however I do not know if the participant wasn't created because I wans't using a Civi pricing yet, and that i would have been created before the latest commit if I had tried with pricing (as I may only have tried participation without pricing, and solelly tried membership once I've added pricing)

I this this issue can be closed. 
It was pretty narrow (not like the other fuzzy one I opened) and addressed

Thank's :)
